The "Log editor data" button should copy to the clipboard if clicked with Alt/Option
ckeditor/ckeditor5-inspector pull request #137
Opened 2021-12-02 16:26 UTC by oleq

Feature: The "Log editor data" button should copy to the clipboard if clicked with Alt/Option. Closes #136.

![](https://user-images.githubusercontent.com/1099479/144462154-134866aa-a786-4a64-a849-70bef316720c.gif)

2021-12-07 09:54 UTC, przemyslaw-zan requested changes
Perhaps `svg` names could be clearer?

- `clipboard` -> `copy-to-clipboard`
- `tick` -> `checkmark`

As far as functionality is concerned, it seems to works as expected. However, if `alt` is pressed and then released without using the button, Chrome switches focus to options button, and Firefox toggles options bar. I suppose we don't want to intercept that, since that is default key behavior on these browsers, but perhaps we could consider different key than `alt`? `shift` and `ctrl` do not trigger any additional behavior. Not sure about that one, maybe i'm looking too deep into this.

2021-12-07 09:54 UTC, przemyslaw-zan commented on src/editorquickactions.css
> +		/* The tick icon shows up when the content was copied to clipboard */
```suggestion
		/* The checkmark icon shows up when the content was copied to clipboard */
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on src/editorquickactions.js
> +import TickIcon from './assets/img/tick.svg';
```suggestion
import CopyToClipboardIcon from './assets/img/copy-to-clipboard.svg';
import CheckmarkIcon from './assets/img/checkmark.svg';
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on src/editorquickactions.js
> +			icon = this.state.isAltKeyPressed ? <ClipboardIcon /> : <SourceIcon />;
```suggestion
			icon = this.state.isAltKeyPressed ? <CopyToClipboardIcon /> : <SourceIcon />;
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on tests/inspector/editorquickactions.js
> +import TickIcon from '../../src/assets/img/tick.svg';
```suggestion
import CopyToClipboardIcon from '../../src/assets/img/copy-to-clipboard.svg';
import CheckmarkIcon from '../../src/assets/img/checkmark.svg';
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on tests/inspector/editorquickactions.js
> +				expect( logButton.props().icon.type ).to.equal( ClipboardIcon );
```suggestion
				expect( logButton.props().icon.type ).to.equal( CopyToClipboardIcon );
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on tests/inspector/editorquickactions.js
> +				expect( logButton.props().icon.type ).to.equal( TickIcon );
```suggestion
				expect( logButton.props().icon.type ).to.equal( CheckmarkIcon );
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on tests/inspector/editorquickactions.js
> +				// Make sure the tick icon + text stay for 3000ms.
```suggestion
				// Make sure the checkmark icon + text stay for 3000ms.
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on tests/inspector/editorquickactions.js
> +				expect( logButton.props().icon.type ).to.equal( TickIcon );
```suggestion
				expect( logButton.props().icon.type ).to.equal( CheckmarkIcon );
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on tests/inspector/editorquickactions.js
> +				// Wait for the tick icon + text to disappear.
```suggestion
				// Wait for the checkmark icon + text to disappear.
```

2021-12-07 09:54 UTC, przemyslaw-zan commented on tests/inspector/editorquickactions.js
> +				expect( logButton.props().icon.type ).to.equal( ClipboardIcon );
```suggestion
				expect( logButton.props().icon.type ).to.equal( CopyToClipboardIcon );
```

2021-12-07 12:35 UTC, oleq commented
Thanks for the review @przemyslaw-zan.

> As far as functionality is concerned, it seems to works as expected. However, if `alt` is pressed and then released without using the button, Chrome switches focus to options button, and Firefox toggles options bar, both of which is somewhat annoying - this could cause poor user experience IMO.

What do you mean by "options button" and "options bar"? Is it the UI of the web browser? Because I only tested on Chrome/FF on Mac and there's nothing exceptional happening. Is it an OS thing maybe?

2021-12-07 12:37 UTC, oleq commented
As for the changes in the code, feel free to commit them straight to the PR. They make sense :)

2021-12-07 16:37 UTC, przemyslaw-zan commented
@oleq sorry for not specifying, yes, i meant UI of the browsers, and the behavior happens on Windows

2021-12-07 19:37 UTC, przemyslaw-zan commented
Firefox: (Options bar toggles on and off)

![](https://user-images.githubusercontent.com/69513154/145093940-7da8c58a-dbd2-4dc4-b072-616f6fafe3ae.gif)

Chrome: (Options button takes focus and prevents further use)

![](https://user-images.githubusercontent.com/69513154/145094590-e5bb32c0-ea46-4c1c-b942-f2421f388ce4.gif)

2021-12-08 08:30 UTC, oleq commented
I didn't anticipate that. Nice catch 👍 

I see three options now:

*   Stick with Alt (because it's alternate after all) but `preventDefault` the event
    *   👎 This will break native browser features that you mentioned,
    *   👎 This would also break other features in the editor like typing accents (ąęśćżźćół...),
        *   OTOH... I think I already detect when the Alt key is being pressed "solo" only, so maybe this would not happen. Needs to be checked.
*   Stick with Alt but `preventDefault` the event only when the inspector is being hovered
    *   👍 Not breaking native browser features most of the time,
    *   👍 Not breaking accents (most of the time)
        *   Or not at all, see my comment in the previous strategy.
    *   👎 Yet breaking both 👆 occasionally (accidentally), which is not a great UX. Quite a surprise when sometimes you can type things and sometimes you cannot.
    *   👎 Annoying if you move the cursor from the top of the page into inspector because the button will change the icon very late.
    *   👎 More complexity in the code.
*   Switch to Shift or Ctrl
    *   👍 Not breaking anything this time, I hope.
    *   👍 Low cost of implementation.
    *   👎 Not very intuitive because clearly, the alternate key should... alternate the features. It's a very common pattern, at least on Mac.

Which sounds best to you? I'm lazy so I'd rather go with Shift/Ctrl if confirmed safe.

2021-12-08 08:44 UTC, przemyslaw-zan commented
I agree with you on the last option being the best. Personally, I think that `ctrl` is the next best choice.

2021-12-21 15:31 UTC, oleq commented
FYI: I used `Shift` instead of `Ctrl`. Turns out, Ctrl+Click is already intercepted and opens the native "right click" context menu. If I went with Ctrl, I'd have to `preventDefault` the `'contextmenu'` event which sounds like unnecessary trouble.

2021-12-22 13:28 UTC, przemyslaw-zan approved these changes
LGTM

2022-02-03 10:53 UTC, merged